export const cities = [
  { title: "Все", slug: "All" },
  { title: "Киев", slug: "kyiv" },
  { title: "Харьков", slug: "kharkiv" },
  { title: "Днепр", slug: "dnipro" },
  { title: "Бровары", slug: "brovary" },
  { title: "Вишневое", slug: "vyshneve" },
  { title: "Житомир", slug: "zhytomyr" },
  { title: "Ужгород", slug: "uzhgorod" },
  { title: "Полтава", slug: "poltava" },
  { title: "Вышгород", slug: "vyshgorod" },
  { title: "Черкассы", slug: "cherkasy" },
  { title: "Каменское", slug: "kamyanske" },
  { title: "Одесса", slug: "Odessa" },
  { title: "Валки", slug: "valky" },
  { title: "Львов", slug: "lviv" },
  { title: "Авдеевка", slug: "avdiyivka" },
  { title: "Ирпень", slug: "irpin" },
  { title: "Васильков", slug: "vasylkiv" },
  { title: "Тернополь", slug: "ternopil" },
];
